version: '3.8'

services:
  tor:
    build: ./tor
    container_name: tor
    restart: always
    volumes:
      - ./tor:/var/lib/tor
    ports:
      - 80:80
  scrapper:
    build: ./app
    container_name: scrapper
    restart: unless-stopped
    environment:
      NOSTR_NSEC: ${NOSTR_NSEC}
    volumes:
      - ./app/data:/app/data:rw
    network_mode: service:tor
  nostr:
    build: ./strfry
    restart: always
    volumes:
      - ./strfry/onion_urls.txt:/app/onion_urls.txt:ro
      - ./strfry/config/strfry.conf:/etc/strfry.conf:ro
      - ./strfry/db:/app/strfry-db:rw
    network_mode: service:tor
